version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${DJANGO_DB_PORT}:5432/tcp"
    volumes:
      - postgresData:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: "${POSTGRES_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

  web:
    build: ./places_remember
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./places_remember:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres


volumes:
  postgresData: